/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteRouteImport } from './routes/admin.route'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminSecoesRouteImport } from './routes/admin.secoes'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as AdminProjetosIndexRouteImport } from './routes/admin.projetos.index'
import { Route as AdminProjetosIdRouteImport } from './routes/admin.projetos.$id'
import { Route as AdminProjetosNovoRouteImport } from './routes/admin.projetos.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecoesRoute = AdminSecoesRouteImport.update({
  id: '/secoes',
  path: '/secoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjetosIndexRoute = AdminProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjetosIdRoute = AdminProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjetosNovoRoute = AdminProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/secoes': typeof AdminSecoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/admin/projetos/$id': typeof AdminProjetosIdRoute
  '/admin/projetos/novo': typeof AdminProjetosNovoRoute
  '/admin/projetos/': typeof AdminProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/secoes': typeof AdminSecoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/admin/projetos/$id': typeof AdminProjetosIdRoute
  '/admin/projetos/novo': typeof AdminProjetosNovoRoute
  '/admin/projetos': typeof AdminProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/sobre': typeof SobreRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/secoes': typeof AdminSecoesRoute
  '/admin_/login': typeof AdminLoginRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/admin/projetos/$id': typeof AdminProjetosIdRoute
  '/admin/projetos/novo': typeof AdminProjetosNovoRoute
  '/admin/projetos/': typeof AdminProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/secoes'
    | '/admin/login'
    | '/projetos/$slug'
    | '/admin/'
    | '/projetos/'
    | '/admin/projetos/$id'
    | '/admin/projetos/novo'
    | '/admin/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/secoes'
    | '/admin/login'
    | '/projetos/$slug'
    | '/admin'
    | '/projetos'
    | '/admin/projetos/$id'
    | '/admin/projetos/novo'
    | '/admin/projetos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/$'
    | '/sobre'
    | '/admin/configuracoes'
    | '/admin/secoes'
    | '/admin_/login'
    | '/projetos/$slug'
    | '/admin/'
    | '/projetos/'
    | '/admin/projetos/$id'
    | '/admin/projetos/novo'
    | '/admin/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  SobreRoute: typeof SobreRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/secoes': {
      id: '/admin/secoes'
      path: '/secoes'
      fullPath: '/admin/secoes'
      preLoaderRoute: typeof AdminSecoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projetos/': {
      id: '/admin/projetos/'
      path: '/projetos'
      fullPath: '/admin/projetos/'
      preLoaderRoute: typeof AdminProjetosIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projetos/$id': {
      id: '/admin/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/admin/projetos/$id'
      preLoaderRoute: typeof AdminProjetosIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projetos/novo': {
      id: '/admin/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/admin/projetos/novo'
      preLoaderRoute: typeof AdminProjetosNovoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminSecoesRoute: typeof AdminSecoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProjetosIdRoute: typeof AdminProjetosIdRoute
  AdminProjetosNovoRoute: typeof AdminProjetosNovoRoute
  AdminProjetosIndexRoute: typeof AdminProjetosIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminSecoesRoute: AdminSecoesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProjetosIdRoute: AdminProjetosIdRoute,
  AdminProjetosNovoRoute: AdminProjetosNovoRoute,
  AdminProjetosIndexRoute: AdminProjetosIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  SobreRoute: SobreRoute,
  AdminLoginRoute: AdminLoginRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
